.TH SNAKE 1 "July 2024" "version 1.0" "Snake Game Manual"
.SH NAME
snake \- A simple command line Snake game.
.SH SYNOPSIS
.B snake
.RI [ OPTIONS ]
.SH DESCRIPTION
.B snake
is a command line Snake game where you control a snake to collect fruit. The game supports three difficulty levels.

.SH OPTIONS
.TP
.B \-e
Start the game in easy mode. The game speed is constant and slow.
.TP
.B \-m
Start the game in medium mode. The game speed increases slightly with each fruit collected.
.TP
.B \-h
Start the game in hard mode. The game speed increases more significantly with each fruit collected.
.SH CONTROLS
.TP
.B Arrow keys
Use the arrow keys to control the direction of the snake.
.TP
.B q
Press 'q' to quit the game.
.SH EXAMPLES
.TP
.B snake \-e
Start the game in easy mode.
.TP
.B snake \-m
Start the game in medium mode.
.TP
.B snake \-h
Start the game in hard mode.
.SH AUTHOR
Written by Brad Hebert.
